version: "3.3"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    tty: true
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    user: "1000:1000"
    # command: sh -c "npm install && npm run dev"
    # env_file:
    #   - frontend/.env.local
